In [ ]:
# Практическое задание №5

# 5.1 Вектор – это частный случай матрицы 1хN и Nх1. Повторите материал для векторов, уделяя особое внимание умножению A∙B.
#     Вычислите, по возможности не используя программирование: (5Е)–1, где Е – единичная матрица размера 5х5.

In [3]:
import numpy as np
def print_matrix(a):
    max_len = max([len(str(e)) for r in a for e in r])
    for row in a:
        print(*'|', *list(map('{{:>{length}}}'.format(length=max_len+1).format, row)), '|')
        
        
E = np.eye(5)
Z = np.linalg.inv(5*E)
print_matrix(Z)

|   0.2   0.0   0.0   0.0   0.0 |
|   0.0   0.2   0.0   0.0   0.0 |
|   0.0   0.0   0.2   0.0   0.0 |
|  -0.0  -0.0  -0.0   0.2  -0.0 |
|   0.0   0.0   0.0   0.0   0.2 |


In [ ]:
# 5.2 Вычислите определитель матрицы

In [4]:
import numpy as np
def print_matrix(a):
    max_len = max([len(str(e)) for r in a for e in r])
    for row in a:
        print(*'|', *list(map('{{:>{length}}}'.format(length=max_len+1).format, row)), '|')

A = np.array([
    [1, 2, 3],
    [4, 0, 6],
    [7, 8, 9],
])
print("Определитель матрицы:")
print_matrix(A)
print('Равен: ', round(np.linalg.det(A), 3))

Определитель матрицы:
|  1  2  3 |
|  4  0  6 |
|  7  8  9 |
Равен:  60.0


In [ ]:
# 5.3.1 Вычислите матрицу, обратную данной

In [5]:
import numpy as np
def print_matrix(a):
    max_len = max([len(str(e)) for r in a for e in r])
    for row in a:
        print(*'|', *list(map('{{:>{length}}}'.format(length=max_len+1).format, row)), '|')

print('Ответ: ')
print(np.linalg.inv(A))

Ответ: 
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


In [ ]:
# 5.3.2 Приведите пример матрицы 4х4, ранг которой равен 1 

In [9]:
import numpy as np
def print_matrix(a):
    max_len = max([len(str(e)) for r in a for e in r])
    for row in a:
        print(*'|', *list(map('{{:>{length}}}'.format(length=max_len+1).format, row)), '|')
        
С = np.array([
    [2, -2, 2, -2],
    [-2, 2, -2, 2],
    [2, -2, 2, -2],
    [-2, 2, -2, 2],
])
print('Матрица: ')
print_matrix(С)
print('Имеет ранг', np.linalg.matrix_rank(С))        

Матрица: 
|   2  -2   2  -2 |
|  -2   2  -2   2 |
|   2  -2   2  -2 |
|  -2   2  -2   2 |
Имеет ранг 1


In [ ]:
# 5.4 Вычислите скалярное произведение двух векторов

In [10]:
a = np.array([1, 5])
b = np.array([2, 8])
print('Ответ: ', np.dot(a, b))

Ответ:  42


In [ ]:
# 5.5 Вычислите смешанное произведение трех векторов (1, 5, 0), (2, 8, 7) и (7, 1.5, 3)

In [26]:
a = np.array([1, 5, 0])
b = np.array([2, 8, 7])
c = np.array([7, 1.5, 3])

print('Ответ: ', np.dot(a, (b * c)))

Ответ:  74.0


In [ ]:
# Практическое задание №6

# 1. Решите линейную систему

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 0, 6],
    [7, 8, 9],
])
b = np.array([12, 2, 1])
X1 = np.dot(np.linalg.inv(A), b) #Решение через обратную матрицу
X2 = np.linalg.solve(A, b) #Решение численным методом

#print(X1, X2)
print('Ответ', X1)

Ответ [-9.2         0.9         6.46666667]


In [ ]:
# 2. Найдите псевдорешение
x + 2y – z = 1
3x – 4y = 7
8x – 5y + 2z = 12
2x – 5z = 7
11x +4y – 7z = 15

In [28]:
A = np.array([
    [1, 2, -1],
    [3, -4, 0],
    [8, -5, 2],
    [2, 0, -5],
    [11, 4, -7],
])
b = np.array([1, 7, 12, 7, 15])
X = np.dot(np.linalg.pinv(A), b)
print('Ответ: ', X)

Ответ:  [ 1.13919353 -0.90498444 -0.9009803 ]


In [29]:
print('Проверка псевдорешения')
print('1 ~ ', 1 * X[0] + 2 * X[1] - 1 * X[2])
print('7 ~ ', 3 * X[0] - 4 * X[1] + 0 * X[2])
print('12 ~ ', 8 * X[0] - 5 * X[1] + 2 * X[2])
print('7 ~ ', 2 * X[0] + 0 * X[1] - 5 * X[2])
print('15 ~ ', 11 * X[0] + 4 * X[1] - 7 * X[2])

Проверка псевдорешения
1 ~  0.2302049464546465
7 ~  7.037518339240221
12 ~  11.836509811711322
7 ~  6.783288552480718
15 ~  15.218053130652056


In [ ]:
#  3. Сколько решений имеет линейная система.
#  Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.

In [31]:
def solve_slau(A, b):
    detA = round(np.linalg.det(A), 8)
    #print(detA)
    def _i_det(M, v, i):
        Mi = M.copy()
        Mi[:,i] = v
        detMi = round(np.linalg.det(Mi), 8)
        return detMi

    detA1 = _i_det(A, b, 0)
    detA2 = _i_det(A, b, 1)
    detA3 = _i_det(A, b, 2)
    
    #print(detA1, detA2, detA3)
    if detA != 0:
        print('Система имеет одно решение')
        return np.linalg.solve(A, b)
    else:
        if (detA1 == 0) & (detA2 == 0) & (detA3 == 0):
            print('Система бесконечное число решений. Система совместна и неопределённа')
            return np.linalg.solve(A, b)
        else:
            print('Система не имеет решений. Система несовместна')
            return None
        
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
b = np.array([12, 2, 1])


solve_slau(A, b)

Система не имеет решений. Система несовместна


In [32]:
c = np.array([8, 20, 32])
solve_slau(A, c)

Система бесконечное число решений. Система совместна и неопределённа


array([-0.8,  5.6, -0.8])

In [ ]:
#  4. Вычислите LU-разложение матрицы:
#  После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [33]:
from scipy.linalg import lu


A = np.array([
    [1, 2, 3],
    [2, 16, 21],
    [4, 28, 73],
])
P, L, U = lu(A)

print('p:\n', P,'\n\nL:\n', L,'\n\nU:\n', U)

p:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

L:
 [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]] 

U:
 [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [34]:
b = np.array([4, 5, 6])
y = np.linalg.solve(L, b)
X = np.linalg.solve(U, y)
print(X)

[ 5.7962963  -0.00925926 -0.25925926]


In [ ]:
#  5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
#  Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.

In [35]:
def Q(x, y, z):
    return np.linalg.norm(np.array([x, y, z]))

A = np.array([
    [1, 2, -1],
    [8, -5, 2],
])
B = np.array([1,12])

print(Q(1, 2, -1))
print(Q(8, -5, 2))

#detA = np.linalg.det(A)
print(np.linalg.lstsq(A,B))

2.449489742783178
9.643650760992955
(array([ 1.38191882, -0.18081181,  0.0202952 ]), array([], dtype=float64), 2, array([9.65316119, 2.41173777]))


C:\Users\73B5~1\AppData\Local\Temp/ipykernel_17228/1074857616.py:14: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  print(np.linalg.lstsq(A,B))


In [ ]:
#  6. Найдите одно из псевдорешений вырожденной системы. Попробуйте также отыскать и нормальное псевдорешение.

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])
B = np.array([2,5,11])

print(np.linalg.lstsq(A,B))

(array([ 1.25,  0.5 , -0.25]), array([], dtype=float64), 2, array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))


C:\Users\73B5~1\AppData\Local\Temp/ipykernel_17228/1620531041.py:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  print(np.linalg.lstsq(A,B))
